Messages:
  notEnoughArgs: '&b[&cForja&b] &eNo has especificado suficientes argumentos.'
  noPermission: '&b[&cForja&b] &eNo tienes permiso para hacer esto.'
  itemGiven: '&b[&cForja&b] &eHas dado %item% &ea %player%.'
  itemGivenPlayer: '&b[&cForja&b] &eHas conseguido un %item%&e.'
  itemGiveArgs: '&b[&cForja&b] &eEl uso es /hephaestusforge give <Objeto> [Jugador]'
  itemNotFound: '&b[&cForja&b] &eNo se ha encontrado el objeto %item%.'
  itemUsed: '&b[&cForja&b] &eObjeto usado con éxito.'
  itemAdded: '&b[&cForja&b] &eObjeto añadido con éxito.'
  itemAlreadyExists: '&b[&cForja&b] &eEl objeto con el identificador %identifier% ya existe.'
  reload: '&b[&cForja&b] &eSe ha recargado la configuración del plugin.'
  help:
    - "&d-===- &c[Forja] &d-===-"
    - "&b/hephaestusforge &eMuestra esta página."
    - "&b/hephaestusforge give <Objeto> [Jugador] &eDa un objeto a un jugador."
    - "&b/hephaestusforge addItem <Identificador> &eAñade un objeto al archivo de objetos."
    - "&b/hephaestusforge reload &eRecarga el plugin."
    - "&b"
    - "&eLeyenda: &b<> &eObligatorio  &b[] &eOpcional"

Wandering:
  chance: 2
  maxExtraTrades: 3
  villager:
    name: "&f&lMercader olímpico"
    glow: true
  trades:
    example:
      weight: 1
      maxUses: 1
      result:
        type: material
        item: BEDROCK
        amount: 1
      ingredients:
        1:
          type: material
          item: NETHER_STAR
          amount: 4
        2:
          type: material
          item: OBSIDIAN
          amount: 8

Piglin:
  vanillaPiglinWeight: 459
  interestItems:
    - EMERALD
    - LAPIS_LAZULI
    - DIAMOND
    - QUARTZ
    - AMETHYST_SHARD
    - COPPER_INGOT
    - IRON_INGOT
    - NETHERITE_INGOT
    - ECHO_SHARD
    - RESIN_CLUMP
  trades:
    example:
      weight: 200
      type: material
      item: BEDROCK
      amount: 4
    example2:
      weight: 250
      type: material
      item: DRAGON_EGG
      amount: 2

# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/loot/LootTables.html
LuckLevelMultiplier: 0.5
LootTables:
  BURIED_TREASURE:
    example:
      chance: 0.1
      type: material
      item: DRAGON_EGG
      min: 1
      max: 1
    example2:
      chance: 1
      type: material
      item: DIAMOND
      min: 1
      max: 2
  END_CITY_TREASURE:
    example:
      chance: 0.5
      type: material
      item: ELYTRA
      min: 1
      max: 1
  DESERT_PYRAMID:
    example:
      chance: 50
      type: material
      item: BEDROCK
      min: 1
      max: 5

Items:
  example:
    material: STONE
    name: "&dExample item"
    lore:
      - ""
      - "&7Example lore."
    commands:
      - "bc test %player%"
    glow: true